## How to represent text for AI


In [1]:
import numpy as np

def one_hot_encoding(sentence):
    words = sentence.lower().split()
    vocab = sorted(set(words))
    words_to_index = {word: idx for idx, word in enumerate(vocab)}
    one_hot_matrix = np.zeros((len(words), len(vocab)), dtype=int)
    for i, word in enumerate(words):
        one_hot_matrix[i, words_to_index[word]] = 1

    return one_hot_matrix, vocab

sentence = "I want to go to Berkeley this summer"
one_hot_matrix, voc = one_hot_encoding(sentence)
print("Vocabulary:", voc)
print("One-hot encoded matrix:\n", one_hot_matrix)

Vocabulary: ['berkeley', 'go', 'i', 'summer', 'this', 'to', 'want']
One-hot encoded matrix:
 [[0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]]


In [2]:
def bag_of_words(sentences):
    tokenized_sentences = [sentence.lower().split() for sentence in sentences]
    flat_words = [word for sentence in tokenized_sentences for word in sentence]
    vocab = sorted(set(flat_words))
    words_to_index = {word: idx for idx, word in enumerate(vocab)}
    bow_matrix = np.zeros((len(sentences), len(vocab)), dtype=int)
    for i, sentence in enumerate(tokenized_sentences):
        for word in sentence:
            if word in words_to_index:
                bow_matrix[i, words_to_index[word]] += 1
    return bow_matrix, vocab

corpus = ["I'm not confident about my knowledge of machine learning.",
          "I want to learn more about deep learning and neural networks.",
            "I have some experience with data science but want to improve."]

bow_matrix, vocab = bag_of_words(corpus)
print("Vocabulary:", vocab)
print("Bag-of-Words matrix:\n", bow_matrix)

Vocabulary: ['about', 'and', 'but', 'confident', 'data', 'deep', 'experience', 'have', 'i', "i'm", 'improve.', 'knowledge', 'learn', 'learning', 'learning.', 'machine', 'more', 'my', 'networks.', 'neural', 'not', 'of', 'science', 'some', 'to', 'want', 'with']
Bag-of-Words matrix:
 [[1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 1 1 0]
 [0 0 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]]


In [3]:
def compute_tf(sentences):
    vocab = sorted(set(word for sentence in sentences for word in sentence.lower().split()))
    words_to_index = {word: idx for idx, word in enumerate(vocab)}
    tf_matrix = np.zeros((len(sentences), len(vocab)), dtype=np.float32)
    for i, sentence in enumerate(sentences):
        words = sentence.lower().split()
        word_count = len(words)
        for word in words:
            if word in words_to_index:
                tf_matrix[i, words_to_index[word]] += 1 / word_count

    return tf_matrix, vocab

def compute_idf(sentences, voc):
    num_docs = len(sentences)
    idf_vector = np.zeros(len(voc), dtype=np.float32)
    words_index = {word: idx for idx, word in enumerate(voc)}
    for word in voc:
        df = sum(1 for sentence in sentences if word in sentence.lower().split())
        idf_vector[words_index[word]] = np.log(num_docs / (df + 1)) + 1

    return idf_vector

def compute_tfidf(sentences):
    tf_matrix, vocab = compute_tf(sentences)
    idf_vector = compute_idf(sentences, vocab)
    tfidf_matrix = tf_matrix * idf_vector
    return tfidf_matrix, vocab

tfidf_matrix, vocab = compute_tfidf(corpus)
print("Vocabulary:", vocab)
print("TF-IDF matrix:\n", tfidf_matrix)
      

Vocabulary: ['about', 'and', 'but', 'confident', 'data', 'deep', 'experience', 'have', 'i', "i'm", 'improve.', 'knowledge', 'learn', 'learning', 'learning.', 'machine', 'more', 'my', 'networks.', 'neural', 'not', 'of', 'science', 'some', 'to', 'want', 'with']
TF-IDF matrix:
 [[0.11111111 0.         0.         0.1561628  0.         0.
  0.         0.         0.         0.1561628  0.         0.1561628
  0.         0.         0.1561628  0.1561628  0.         0.1561628
  0.         0.         0.1561628  0.1561628  0.         0.
  0.         0.         0.        ]
 [0.09090909 0.12776956 0.         0.         0.         0.12776956
  0.         0.         0.09090909 0.         0.         0.
  0.12776956 0.12776956 0.         0.         0.12776956 0.
  0.12776956 0.12776956 0.         0.         0.         0.
  0.09090909 0.09090909 0.        ]
 [0.         0.         0.12776956 0.         0.12776956 0.
  0.12776956 0.12776956 0.09090909 0.         0.12776956 0.
  0.         0.         0.    

## Embedding, application and representation